on:
  push:
    branches:
    - release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run publish script
        run: bash publish.sh
      - name: Commit version increase
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Incrementing version
          branch: main
